### ISSUE TITLE
fatal error when use vcf file

### ISSUE THREAD

**Issue by serge2016** [hammerlab/immuno#173]
Hello. Could you help me, please?
$ python /mnt/data2/serge/soft/immuno-master/immuno/mutation_report.py --input-file KPL4.FS30-QD2-cluster3-w35.vcf --vaccine-peptide-length 19
Traceback (most recent call last):
  File "/mnt/data2/serge/soft/immuno-master/immuno/mutation_report.py", line 246, in <module>
    load_file(input_filename, max_peptide_length = peptide_length)
  File "/mnt/data2/serge/soft/immuno-master/immuno/load_file.py", line 300, in load_file
    vcf_df = load_variants(input_filename)
  File "/mnt/data2/serge/soft/immuno-master/immuno/load_file.py", line 256, in load_variants
    vcf_df = load_vcf(input_filename)
  File "/mnt/data2/serge/soft/immuno-master/immuno/vcf.py", line 73, in load_vcf
    mask = (qual == 'PASS') | (qual == '.')
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 614, in wrapper
    res = na_op(values, other)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/ops.py", line 568, in na_op
    raise TypeError("invalid type comparison")
TypeError: invalid type comparison

**Comment by iskandr** [comment]
Hey @serge2016, 

This repo was our first prototype but we've since split the logic into several other projects. Check out: https://github.com/hammerlab/topiary
